cmake_minimum_required(VERSION 4.2)
project(Codeforces___Leetcode)

set(CMAKE_CXX_STANDARD 20)

add_executable(
        Leetcode1 Leetcode/Leetcode1.cpp
        Leetcode/Leetcode13.cpp
        Leetcode/Leetcode169.cpp
        Leetcode/Leetcode914.cpp
        Codeforces/Codeforces-Boyer-Moore-Lab3.cpp
)
#fuck my hb merx